name: cli_help
description: Trivial Dart package for serving command-line help from helptext.txt
version: 1.0.1
publish_to: none

repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
